Universe         = vanilla
RequestCpus     = 1
RequestMemory    = 15G
+RequestWalltime = 518400

#request_GPUs = 1
#requirements = (CUDAGlobalMemoryMb >= 3000) && (CUDACapability >= 3.5) 

NiceUser = true
Notification = Error
initialdir = ../.

executable = /users/start2014/r0385169/bin/python
arguments = "create_new_batch_files.py"

Log          = temp.log
Output       = temp.out
Error        = temp.err

Queue

