Universe         = vanilla
RequestCpus     = 1
RequestMemory    = 4G
+RequestWalltime = 518400

request_GPUs = 1
requirements = (CUDAGlobalMemoryMb >= 4000) && (CUDACapability >= 3.5) && (machine != "spchcl18.esat.kuleuven.be")

Notification = Error
initialdir = .

executable = /users/start2014/r0385169/bin/python
arguments = "lm_cbow_soft_$(data_set)_test.py --test_name=$(test_name) --num_run=$(num_run)"

Log          = jobdag/$(data_set)_test_$(test_name)_$(num_run).log
Output       = jobdag/$(data_set)_test_$(test_name)_$(num_run).out
Error        = jobdag/$(data_set)_test_$(test_name)_$(num_run).err

Queue

