Universe         = vanilla
RequestCpus     = 1
RequestMemory    = 2G
+RequestWalltime = 518400

request_GPUs = 1
requirements = (CUDAGlobalMemoryMb >= 2000) && (CUDACapability >= 3.5)

NiceUser = true
Notification = Error
initialdir = .

executable = /users/start2014/r0385169/bin/python
arguments = "lm_cbow_soft_ds_test.py"

Log          = jobdag/temp.log
Output       = jobdag/temp.out
Error        = jobdag/temp.err

Queue

